language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"
script:
  - docker-compose -f Docker-compose-build.yaml build --parallel

  - docker tag udagram-api-feed giabaohb48/udagram-api-feed:latest
  - docker tag udagram-api-user giabaohb48/udagram-api-user:latest
  - docker tag udagram-frontend giabaohb48/udagram-frontend:latest
  - docker tag udagram-reverseproxy giabaohb48/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push giabaohb48/udagram-api-feed:latest
  - docker push giabaohb48/udagram-api-user:latest
  - docker push giabaohb48/udagram-frontend:latest
  - docker push giabaohb48/udagram-reverseproxy:latest
